// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh9duAJX4cuXv0-Y1VRgnS93AO51de1RQ',
    appId: '1:803479690583:web:6bc2bfa945789864533212',
    messagingSenderId: '803479690583',
    projectId: 'autopro-app-flutter',
    authDomain: 'autopro-app-flutter.firebaseapp.com',
    storageBucket: 'autopro-app-flutter.appspot.com',
    measurementId: 'G-5XYL1BXGVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcP1kDvi9oTJwNvaIJdNo-uxoo3p377-c',
    appId: '1:803479690583:android:ecafadb97b176849533212',
    messagingSenderId: '803479690583',
    projectId: 'autopro-app-flutter',
    storageBucket: 'autopro-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdQRv8ZgPsfC2rM6BedYvN4yDWqnrDxTw',
    appId: '1:803479690583:ios:5f38b99278d61f88533212',
    messagingSenderId: '803479690583',
    projectId: 'autopro-app-flutter',
    storageBucket: 'autopro-app-flutter.appspot.com',
    iosBundleId: 'com.example.autoprocfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdQRv8ZgPsfC2rM6BedYvN4yDWqnrDxTw',
    appId: '1:803479690583:ios:c0a648bd68d49834533212',
    messagingSenderId: '803479690583',
    projectId: 'autopro-app-flutter',
    storageBucket: 'autopro-app-flutter.appspot.com',
    iosBundleId: 'com.example.autoprocfinal.RunnerTests',
  );
}
